# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-02-28 11:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0004_auto_20190228_1418'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='article_image',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='articles/'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='image',
            name='category',
            field=models.ManyToManyField(to='photos.Category'),
        ),
    ]
