# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-03-03 12:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0005_auto_20190228_1454'),
    ]

    operations = [
        migrations.RenameField(
            model_name='image',
            old_name='article_image',
            new_name='image_url',
        ),
        migrations.RenameField(
            model_name='image',
            old_name='image_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='location',
            old_name='location_name',
            new_name='name',
        ),
        migrations.AlterField(
            model_name='image',
            name='category',
            field=models.ManyToManyField(to='photos.Category'),
        ),
    ]
